### ISSUE TITLE
iban_isValidSEPA() return false for NL** IBANs

### ISSUE THREAD

**Issue by TheStalwart** [stefan-sedlak/IBAN#1]
According to other IBAN validators i tested, SEPA should be enabled for Netherlands. This library however contains the following definition:

{.country_code = {'N', 'L'}, .length = 18, .is_sepa = false},

I assume it's a bug

**Comment by stefan-sedlak** [comment]
you are right I will change https://github.com/stefan-sedlak/IBAN/blob/5d5c069bb5b65a4ee6c1d77e4e957a25a1894f0b/IBAN/Classes/iban.c#L118

**Comment by stefan-sedlak** [comment]
fixed by #2 in 1.0.1. I have not published it to cocoapods but you can use it via tag:

**Comment by TheStalwart** [comment]
Will you publish to cocoapods later?

**Comment by stefan-sedlak** [comment]
if it is useful for you then yes. I used the library for Wirecard paymentSDK. but you know the story and I am not Wirecard guy now 😔

**Comment by TheStalwart** [comment]
We had to abandon Wirecard paymentSDK, but still use this library for input validation in UI. Please push it to Cocoapods

**Comment by stefan-sedlak** [comment]
--------------------------------------------------------------------------------
 �  Congrats

 �  IBAN (1.0.1) successfully published
 �  May 26th, 18:43
 �  https://cocoapods.org/pods/IBAN
 �  Tell your friends!
--------------------------------------------------------------------------------
